USE [master]
GO

/****** Object:  Database [eshiftDb]    Script Date: 7/30/2022 3:10:38 PM ******/
DROP DATABASE [eshiftDb]
GO

/****** Object:  Database [eshiftDb]    Script Date: 7/30/2022 3:10:38 PM ******/
CREATE DATABASE [eshiftDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eshiftDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\eshiftDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'eshiftDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\eshiftDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eshiftDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eshiftDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eshiftDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eshiftDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eshiftDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eshiftDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [eshiftDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eshiftDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eshiftDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eshiftDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eshiftDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eshiftDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eshiftDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eshiftDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eshiftDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eshiftDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [eshiftDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eshiftDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eshiftDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eshiftDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eshiftDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eshiftDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eshiftDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eshiftDb] SET RECOVERY FULL 
GO

ALTER DATABASE [eshiftDb] SET  MULTI_USER 
GO

ALTER DATABASE [eshiftDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eshiftDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eshiftDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eshiftDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [eshiftDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [eshiftDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [eshiftDb] SET  READ_WRITE 
GO


